# Generated by Django 2.2.6 on 2019-11-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('pname', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('features', models.CharField(max_length=500)),
            ],
        ),
    ]
