# Generated by Django 2.2.6 on 2019-11-06 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productinfo', '0002_product_mdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='des',
            new_name='desc',
        ),
    ]
